//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS_Services.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.SolicitudCotizacion = new HashSet<SolicitudCotizacion>();
        }
    
        public int id { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string empresa { get; set; }
        public string celular { get; set; }
        public System.DateTime create_at { get; set; }
        public Nullable<int> id_afiliacion { get; set; }
    
        public virtual Afiliacion Afiliacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudCotizacion> SolicitudCotizacion { get; set; }
    }
}
