//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS_Services.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TMS_DBEntities : DbContext
    {
        public TMS_DBEntities()
            : base("name=TMS_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCredencialApiOdoo> tblCredencialApiOdoo { get; set; }
        public virtual DbSet<tblPersona> tblPersona { get; set; }
        public virtual DbSet<tblRol> tblRol { get; set; }
        public virtual DbSet<tblTipoCredencial> tblTipoCredencial { get; set; }
        public virtual DbSet<tblUsuario> tblUsuario { get; set; }
    
        public virtual ObjectResult<sp_accesoAPI_Result> sp_accesoAPI(string username, string pass, Nullable<int> idCredencial)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            var idCredencialParameter = idCredencial.HasValue ?
                new ObjectParameter("idCredencial", idCredencial) :
                new ObjectParameter("idCredencial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_accesoAPI_Result>("sp_accesoAPI", usernameParameter, passParameter, idCredencialParameter);
        }
    
        public virtual ObjectResult<sp_accesoApiOdoo_Result> sp_accesoApiOdoo(string username, string pass, Nullable<int> idCredencial)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            var idCredencialParameter = idCredencial.HasValue ?
                new ObjectParameter("idCredencial", idCredencial) :
                new ObjectParameter("idCredencial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_accesoApiOdoo_Result>("sp_accesoApiOdoo", usernameParameter, passParameter, idCredencialParameter);
        }
    
        public virtual ObjectResult<sp_accesoApiOdoo_Result> accesoApiOdoo(string username, string pass, Nullable<int> idCredencial)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            var idCredencialParameter = idCredencial.HasValue ?
                new ObjectParameter("idCredencial", idCredencial) :
                new ObjectParameter("idCredencial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_accesoApiOdoo_Result>("accesoApiOdoo", usernameParameter, passParameter, idCredencialParameter);
        }
    }
}
