//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS_Services.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoArchivo
    {
        public int id_tarea { get; set; }
        public int id_proyecto { get; set; }
        public System.DateTime create_at { get; set; }
        public string extension { get; set; }
    
        public virtual ConfiguracionTarea ConfiguracionTarea { get; set; }
    }
}
