//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS_Services.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudCotizacion
    {
        public int id { get; set; }
        public int id_cliente { get; set; }
        public int id_servicio { get; set; }
        public Nullable<int> id_tipoCamion { get; set; }
        public Nullable<int> id_rutaOrigen { get; set; }
        public string ciudadOrigen { get; set; }
        public Nullable<int> id_rutaDestino { get; set; }
        public string ciudadDestino { get; set; }
        public Nullable<decimal> pesoCarga { get; set; }
        public Nullable<int> id_unidadPeso { get; set; }
        public Nullable<decimal> volumenCarga { get; set; }
        public Nullable<int> id_unidadVolumen { get; set; }
        public Nullable<bool> imoCarga { get; set; }
        public Nullable<decimal> capacidadAlmacenamiento { get; set; }
        public Nullable<int> id_unidadCapacidad { get; set; }
        public Nullable<decimal> tiempoAlmacenamiento { get; set; }
        public Nullable<int> id_unidadTiempo { get; set; }
        public string comentarios { get; set; }
        public System.DateTime create_at { get; set; }
        public Nullable<int> id_afiliacion { get; set; }
    
        public virtual Afiliacion Afiliacion { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Ruta Ruta { get; set; }
        public virtual Ruta Ruta1 { get; set; }
        public virtual TipoServicio TipoServicio { get; set; }
        public virtual TipoCamion TipoCamion { get; set; }
        public virtual UnidadMedida UnidadMedida { get; set; }
        public virtual UnidadMedida UnidadMedida1 { get; set; }
        public virtual UnidadMedida UnidadMedida2 { get; set; }
        public virtual UnidadMedida UnidadMedida3 { get; set; }
    }
}
