//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS_Services.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transportista_Ruta
    {
        public int id_transportista { get; set; }
        public int id_ruta { get; set; }
        public int estado { get; set; }
        public System.DateTime create_at { get; set; }
    
        public virtual Ruta Ruta { get; set; }
        public virtual Transportista Transportista { get; set; }
    }
}
